=== Khmelov/JD2018-03-22/src/by/it/_examples_/jd02_07/02.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT students (student)+>
<!ELEMENT student (name, nickname, telephone, address)>
<!ATTLIST student
        login ID #REQUIRED
        course CDATA #REQUIRED
        >
<!ELEMENT name (#PCDATA)>
<!ELEMENT nickname (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT address (country, city, street)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT street (#PCDATA)>

=== Khmelov/JD2018-03-22/src/by/it/_examples_/jd02_07/02+DTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM "02.dtd" >
<students>
    <student login="IvanovMitarAlex7" course='it.jd.02'>
        <name>Ivanov Alexander</name>
        <nickname>&quot;M&amp;M&apos;s&quot;</nickname>
        <telephone>4586954</telephone>
        <address>
            <country>Belarus</country>
            <city>Minsk</city>
            <street>Lenina 3</street>
        </address>
    </student>

    <student login="zPav16" course='it.jd.02'>
        <name>Zimin Pavel</name>
        <nickname>&lt;Daemond&gt;</nickname>
        <telephone>2569854</telephone>
        <address>
            <country>Belarus</country>
            <city>Grodno</city>
            <street>Gikalo 21</street>
        </address>
    </student>
</students>
