=== Khmelov/JD2018-03-22/src/by/it/kirova/jd02_07/Booking.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://it-academy.by/kirova"
        xmlns:tns="http://it-academy.by/kirova"
        elementFormDefault="qualified">
    <element name="Booking">
        <complexType>
            <sequence>
                <element name="Users"
                         type="tns:Users"
                         minOccurs="0"
                         maxOccurs="unbounded">
                </element>
                <element name="Reservations"
                         type="tns:Reservations"
                         minOccurs="0"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>

    <complexType name="Users">
        <sequence>
            <element name="User"
                     type="tns:User"
                     minOccurs="0"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="User">
        <sequence>
            <element name="UserId" type="positiveInteger"/>
            <element name="Email" type="string"/>
            <element name="Password" type="string"/>
            <element name="FirstName" type="string"/>
            <element name="LastName" type="string"/>
            <element name="MiddleName" type="string"/>
            <element name="Country" type="string"/>
            <element name="PhoneNumber" type="string"/>
            <element name="Hotels" type="tns:Hotels"/>
            <element name="Reservations" type="tns:Reservations"/>
        </sequence>
    </complexType>

    <complexType name="Hotels">
        <sequence>
            <element name="Hotel"
                     type="tns:Hotel"
                     minOccurs="0"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Hotel">
        <sequence>
            <element name="HotelId" type="positiveInteger"/>
            <element name="Name" type="string"/>
            <element name="Type" type="string"/>
            <element name="StarRating" type="positiveInteger"/>
            <element name="Country" type="string"/>
            <element name="City" type="string"/>
            <element name="Street" type="string"/>
            <element name="HouseNumber" type="string"/>
            <element name="ContactEmail" type="string"/>
            <element name="PhoneNumber" type="string"/>
            <element name="UserId" type="positiveInteger"/>
            <element name="Rooms" type="tns:Rooms"/>
        </sequence>
    </complexType>

    <complexType name="Rooms">
        <sequence>
            <element name="Room"
                     type="tns:Room"
                     minOccurs="0"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Room">
        <sequence>
            <element name="RoomId" type="positiveInteger"/>
            <element name="RoomName" type="string"/>
            <element name="RoomFactNumber" type="string"/>
            <element name="PeopleAmount" type="positiveInteger"/>
            <element name="Description" type="string"/>
            <element name="Cost" type="tns:Cost"/>
            <element name="HotelId" type="positiveInteger"/>
        </sequence>
    </complexType>

    <complexType name="Reservations">
        <sequence>
            <element name="Reservation"
                     type="tns:Reservation"
                     minOccurs="0"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Reservation">
        <sequence>
            <element name="ReservationId" type="positiveInteger"/>
            <element name="ReservationDate" type="date"/>
            <element name="CheckInDate" type="date"/>
            <element name="CheckOutDate" type="date"/>
            <element name="TotalCost" type="tns:TotalCost"/>
            <element name="RoomId" type="positiveInteger"/>
            <element name="UserId" type="positiveInteger"/>
            <element name="Payments" type="tns:Payments"/>
        </sequence>
    </complexType>

    <complexType name="Payments">
        <sequence>
            <element name="Payment"
                     type="tns:Payment"
                     minOccurs="0"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Payment">
        <sequence>
            <element name="PaymentId" type="positiveInteger"/>
            <element name="FirstName" type="string"/>
            <element name="LastName" type="string"/>
            <element name="CreditCardNumber" type="long"/>
            <element name="ExpireDate" type="string"/>
            <element name="ReservationId" type="positiveInteger"/>
        </sequence>
    </complexType>

    <complexType name="Cost">
        <simpleContent>
            <extension base="string">
                <attribute name="cur" type="string" use="required"/>
            </extension>
        </simpleContent>
    </complexType>

    <complexType name="TotalCost">
        <simpleContent>
            <extension base="string">
                <attribute name="cur" type="string" use="required"/>
            </extension>
        </simpleContent>
    </complexType>
</schema>

=== Khmelov/JD2018-03-22/src/by/it/kirova/jd02_07/Booking+XSD.xml
<?xml version="1.0" encoding="utf-8" ?>
<Booking xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://jd02_09.kirova.it.by"
         xsi:schemaLocation="http://jd02_09.kirova.it.by Booking.xsd">
    <Users>
        <User>
            <UserId>1</UserId>
            <Email>abc@gmail.com</Email>
            <Password>abc123</Password>
            <FirstName>Иван</FirstName>
            <LastName>Иванов</LastName>
            <MiddleName>Иванович</MiddleName>
            <Country>Беларусь</Country>
            <PhoneNumber>+375291111111</PhoneNumber>
            <Hotels></Hotels>
        </User>
        <User>
            <UserId>2</UserId>
            <Email>def@gmail.com</Email>
            <Password>def123</Password>
            <FirstName>Александр</FirstName>
            <LastName>Александров</LastName>
            <MiddleName>Александрович</MiddleName>
            <Country>Россия</Country>
            <PhoneNumber>+749597556983</PhoneNumber>
            <Hotels>
                <Hotel>
                    <HotelId>1</HotelId>
                    <Name>Resort Spa</Name>
                    <Type>Отель</Type>
                    <StarRating>5</StarRating>
                    <Country>Россия</Country>
                    <City>Москва</City>
                    <Street>Горького</Street>
                    <HouseNumber>82</HouseNumber>
                    <ContactEmail>spa@gmail.com</ContactEmail>
                    <PhoneNumber>+7395975339983</PhoneNumber>
                    <Rooms>
                        <Room>
                            <RoomId>2</RoomId>
                            <RoomName>Номер с односпальной кроватью</RoomName>
                            <RoomFactNumber>100</RoomFactNumber>
                            <PeopleAmount>1</PeopleAmount>
                            <Description>Завтрак включен в стоимость</Description>
                            <Cost cur="р.">15000</Cost>
                            <Reservations>
                                <Reservation>
                                    <ReservationId>3</ReservationId>
                                    <ReservationDate>2018-05-11</ReservationDate>
                                    <CheckInDate>2018-07-24</CheckInDate>
                                    <CheckOutDate>2018-07-25</CheckOutDate>
                                    <TotalCost cur="р.">15000</TotalCost>
                                    <PaymentStatus>Оплачено</PaymentStatus>
                                    <UserId>5</UserId>
                                </Reservation>
                            </Reservations>
                        </Room>
                        <Room>
                            <RoomId>4</RoomId>
                            <RoomName>Номер с 2 двуспальными кроватями</RoomName>
                            <RoomFactNumber>200</RoomFactNumber>
                            <PeopleAmount>4</PeopleAmount>
                            <Description></Description>
                            <Cost cur="$">40000</Cost>
                            <Reservations></Reservations>
                        </Room>
                    </Rooms>
                </Hotel>
            </Hotels>
        </User>
        <User>
            <UserId>3</UserId>
            <Email>xyz@gmail.com</Email>
            <Password>xyz123</Password>
            <FirstName>John</FirstName>
            <LastName>Smith</LastName>
            <MiddleName></MiddleName>
            <Country>Австрия</Country>
            <PhoneNumber>+447871234567</PhoneNumber>
            <Hotels>
                <Hotel>
                    <HotelId>2</HotelId>
                    <Name>Resort Appartment</Name>
                    <Type>Апартаменты</Type>
                    <StarRating>5</StarRating>
                    <Country>Австрия</Country>
                    <City>Вена</City>
                    <Street>Bahgasse</Street>
                    <HouseNumber>4</HouseNumber>
                    <ContactEmail>wienapart@gmail.com</ContactEmail>
                    <PhoneNumber>+4395975339983</PhoneNumber>
                    <Rooms>
                        <Room>
                            <RoomId>1</RoomId>
                            <RoomName>Апартаменты с терассой</RoomName>
                            <RoomFactNumber></RoomFactNumber>
                            <PeopleAmount>2</PeopleAmount>
                            <Description>Апартаменты в сердце Вены с терассой, двуспальной кроватью и кухней
                            </Description>
                            <Cost cur="$">450</Cost>
                            <Reservations>
                                <Reservation>
                                    <ReservationId>1</ReservationId>
                                    <ReservationDate>2018-03-14</ReservationDate>
                                    <CheckInDate>2018-07-20</CheckInDate>
                                    <CheckOutDate>2018-07-23</CheckOutDate>
                                    <TotalCost cur="$">1350</TotalCost>
                                    <PaymentStatus>Оплачено</PaymentStatus>
                                    <UserId>5</UserId>
                                </Reservation>
                                <Reservation>
                                    <ReservationId>2</ReservationId>
                                    <ReservationDate>2018-04-18</ReservationDate>
                                    <CheckInDate>2018-07-28</CheckInDate>
                                    <CheckOutDate>2018-07-29</CheckOutDate>
                                    <TotalCost cur="$">450</TotalCost>
                                    <PaymentStatus>Оплачено</PaymentStatus>
                                    <UserId>4</UserId>
                                </Reservation>
                            </Reservations>
                        </Room>
                    </Rooms>
                </Hotel>
                <Hotel>
                    <HotelId>3</HotelId>
                    <Name>Spa Appartment</Name>
                    <Type>Апартаменты</Type>
                    <StarRating>5</StarRating>
                    <Country>Австрия</Country>
                    <City>Вена</City>
                    <Street>Johann-Hoffmann Platz</Street>
                    <HouseNumber>16</HouseNumber>
                    <ContactEmail>wienapart@gmail.com</ContactEmail>
                    <PhoneNumber>+4395975339983</PhoneNumber>
                    <Rooms>
                        <Room>
                            <RoomId>3</RoomId>
                            <RoomName>Апартаменты с 2 спальнями</RoomName>
                            <RoomFactNumber></RoomFactNumber>
                            <PeopleAmount>2</PeopleAmount>
                            <Description>Апартаменты в сердце Вены с 2 двуспальными кроватями и кухней</Description>
                            <Cost cur="$">550</Cost>
                            <Reservations></Reservations>
                        </Room>
                    </Rooms>
                </Hotel>
            </Hotels>
        </User>
        <User>
            <UserId>4</UserId>
            <Email>glg@gmail.com</Email>
            <Password>glg123</Password>
            <FirstName>Петр</FirstName>
            <LastName>Петров</LastName>
            <MiddleName>Петрович</MiddleName>
            <Country>Беларусь</Country>
            <PhoneNumber>+375292222222</PhoneNumber>
            <Hotels></Hotels>
        </User>
        <User>
            <UserId>5</UserId>
            <Email>ppp@gmail.com</Email>
            <Password>ppp123</Password>
            <FirstName>Jacob</FirstName>
            <LastName>Irwin</LastName>
            <MiddleName></MiddleName>
            <Country>Польша</Country>
            <PhoneNumber>+485291111111</PhoneNumber>
            <Hotels></Hotels>
        </User>
    </Users>
</Booking>
